# Generated by Django 5.0 on 2023-12-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_inventory_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
    ]
